version: '3.8'

volumes:
  mosquitto-data:

services:

  mqtt:
    image: eclipse-mosquitto:2.0.15
    # user: root
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: on-failure
